/*
 * File: app/view/BatList.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AppBat.view.BatList', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.batlist',

    requires: [
        'AppBat.view.BatListViewModel',
        'Ext.tree.Panel',
        'Ext.tree.View',
        'Ext.form.Panel',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'batlist'
    },
    width: 150,
    layout: 'border',
    title: 'Bâtiments',

    items: [
        {
            xtype: 'treepanel',
            region: 'center',
            viewConfig: {

            }
        },
        {
            xtype: 'form',
            region: 'south',
            height: 70,
            defaults: {
                margin: 5
            },
            layout: {
                type: 'hbox',
                align: 'stretch',
                padding: 5
            },
            items: [
                {
                    xtype: 'button',
                    flex: 1,
                    text: 'MyButton'
                },
                {
                    xtype: 'button',
                    flex: 1,
                    text: 'MyButton'
                }
            ]
        }
    ]

});