/*
 * File: app/view/BatTab.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AppBat.view.BatTab', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.battab',

    requires: [
        'AppBat.view.BatTabViewModel',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.grid.View',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'battab'
    },
    padding: 2,
    layout: 'border',
    title: 'Bâtiments',

    items: [
        {
            xtype: 'gridpanel',
            region: 'center',
            title: '',
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'string',
                    text: 'String'
                },
                {
                    xtype: 'numbercolumn',
                    dataIndex: 'number',
                    text: 'Number'
                },
                {
                    xtype: 'datecolumn',
                    dataIndex: 'date',
                    text: 'Date'
                },
                {
                    xtype: 'booleancolumn',
                    dataIndex: 'bool',
                    text: 'Boolean'
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'east',
            width: 100,
            defaults: {
                margin: 2
            },
            title: 'Filtre',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'button',
                    flex: 1,
                    text: 'Btn1'
                },
                {
                    xtype: 'button',
                    flex: 1,
                    text: 'Btn2'
                },
                {
                    xtype: 'button',
                    flex: 1,
                    text: 'Btn3'
                },
                {
                    xtype: 'button',
                    flex: 1,
                    text: 'Btn4'
                },
                {
                    xtype: 'button',
                    flex: 1,
                    text: 'Btn5'
                }
            ]
        }
    ]

});