/*
 * File: app/view/Etablissement.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AppBat.view.Etablissement', {
    extend: 'Ext.form.Panel',
    alias: 'widget.etablissement',

    requires: [
        'AppBat.view.EtablissementViewModel',
        'Ext.container.Container',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'etablissement'
    },
    height: 200,
    titleAlign: 'center',

    layout: {
        type: 'hbox',
        align: 'stretch'
    },
    items: [
        {
            xtype: 'container',
            flex: 1,
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'textfield',
                    flex: 1,
                    margin: 0,
                    emptyText: 'A005'
                },
                {
                    xtype: 'textfield',
                    flex: 1,
                    margin: 0,
                    emptyText: 'WHE16'
                },
                {
                    xtype: 'textfield',
                    flex: 1,
                    margin: 0,
                    emptyText: 'WHE16'
                },
                {
                    xtype: 'textfield',
                    flex: 1,
                    margin: 0,
                    emptyText: '18052'
                },
                {
                    xtype: 'textfield',
                    flex: 1,
                    margin: 0,
                    emptyText: '18000'
                }
            ]
        },
        {
            xtype: 'container',
            flex: 3,
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            flex: 2,
                            emptyText: 'Ville'
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            emptyText: 'CP'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            flex: 1,
                            emptyText: 'N° Rue'
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            emptyText: 'BTQ'
                        },
                        {
                            xtype: 'textfield',
                            flex: 4,
                            emptyText: 'Nom de la rue'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            flex: 1,
                            emptyText: 'Complément d\'adresse'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            flex: 1,
                            emptyText: 'Ville'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            flex: 1,
                            emptyText: 'Cedex + N°'
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            emptyText: 'N° Lot'
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            emptyText: 'Bât'
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            emptyText: 'Esc.'
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            emptyText: '6'
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            emptyText: 'Appart'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            flex: 4,
            html: 'Google maps'
        },
        {
            xtype: 'container',
            flex: 1,
            layout: {
                type: 'vbox',
                align: 'stretch',
                padding: 5
            },
            items: [
                {
                    xtype: 'button',
                    flex: 1,
                    margin: 5,
                    text: 'Rue'
                },
                {
                    xtype: 'button',
                    flex: 1,
                    margin: 5,
                    text: 'Carte'
                }
            ]
        }
    ]

});