/*
 * File: app/view/InfoGenTab.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AppBat.view.InfoGenTab', {
    extend: 'Ext.form.Panel',
    alias: 'widget.infogentab',

    requires: [
        'AppBat.view.InfoGenTabViewModel',
        'Ext.form.field.Text',
        'Ext.grid.Panel',
        'Ext.grid.column.Column'
    ],

    viewModel: {
        type: 'infogentab'
    },
    title: 'Infos générales',

    layout: {
        type: 'hbox',
        align: 'stretch',
        padding: 2
    },
    items: [
        {
            xtype: 'panel',
            flex: 4,
            frame: true,
            margin: 2,
            defaults: {
                margin: '0 0 5 0'
            },
            title: 'Informations',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'textfield',
                    flex: 1,
                    fieldLabel: 'Au RCS de'
                },
                {
                    xtype: 'container',
                    flex: 1,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            flex: 1,
                            fieldLabel: 'Immatriculé le'
                        },
                        {
                            xtype: 'textfield',
                            flex: 0.8,
                            margin: '0 0 0 5',
                            fieldLabel: 'Radié le',
                            labelWidth: 70
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            flex: 1,
                            fieldLabel: 'Exploité du'
                        },
                        {
                            xtype: 'textfield',
                            flex: 0.8,
                            margin: '0 0 0 5',
                            fieldLabel: 'Jusqu\'au',
                            labelWidth: 70
                        }
                    ]
                },
                {
                    xtype: 'textfield',
                    flex: 1,
                    fieldLabel: 'Origine'
                },
                {
                    xtype: 'textfield',
                    flex: 1,
                    fieldLabel: 'Nace'
                },
                {
                    xtype: 'container',
                    flex: 1,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            flex: 1,
                            emptyText: 'Email'
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            margin: '0 0 0 5',
                            emptyText: 'Tél. fixe'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    flex: 1,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            flex: 1,
                            emptyText: 'Raccourci interne'
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            margin: '0 0 0 5',
                            emptyText: 'Tél. portable'
                        }
                    ]
                },
                {
                    xtype: 'textfield',
                    flex: 1,
                    fieldLabel: 'Type etablissement',
                    labelWidth: 130
                },
                {
                    xtype: 'textfield',
                    flex: 1,
                    fieldLabel: 'Catégorie ERP',
                    labelWidth: 130
                },
                {
                    xtype: 'textfield',
                    flex: 1,
                    fieldLabel: 'Sous catégorie ERP',
                    labelWidth: 130
                },
                {
                    xtype: 'container',
                    flex: 1,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'textfield',
                            flex: 1,
                            fieldLabel: 'Nombre de salariés',
                            labelWidth: 130
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            margin: '0 0 0 5',
                            fieldLabel: 'Nombre de clients',
                            labelWidth: 130
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'container',
            flex: 1,
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'panel',
                    flex: 1,
                    margin: 2,
                    title: 'Localisé en'
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    margin: 2,
                    title: 'Régions'
                }
            ]
        },
        {
            xtype: 'container',
            flex: 2,
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    margin: 2,
                    title: 'Horaires d\'ouverture',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Jour',
                            flex: 1
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'number',
                            text: 'Matin',
                            flex: 1
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'date',
                            text: 'Après midi',
                            flex: 1
                        }
                    ]
                }
            ]
        }
    ]

});