/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AppBat.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'AppBat.view.MainViewViewModel',
        'AppBat.view.MainViewViewController',
        'AppBat.view.Etablissement',
        'AppBat.view.InfoGenTab',
        'AppBat.view.BatTab',
        'AppBat.view.EquipementTab',
        'AppBat.view.ActionTab',
        'AppBat.view.BatList',
        'Ext.form.Panel',
        'Ext.tab.Panel',
        'Ext.tab.Tab'
    ],

    controller: 'mainview',
    viewModel: {
        type: 'mainview'
    },
    layout: 'border',

    items: [
        {
            xtype: 'panel',
            region: 'north',
            height: 50,
            itemId: 'header',
            dockedItems: [
                {
                    xtype: 'panel',
                    dock: 'right',
                    reference: 'loginPanel',
                    items: [
                        {
                            xtype: 'button',
                            margin: 6,
                            text: 'Login',
                            listeners: {
                                click: 'onLoginButtonClick'
                            }
                        },
                        {
                            xtype: 'button',
                            margin: 5,
                            text: 'Register',
                            listeners: {
                                click: 'onRegisterButtonClick'
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    dock: 'right',
                    reference: 'logoutPanel',
                    hidden: true,
                    items: [
                        {
                            xtype: 'button',
                            margin: 6,
                            text: 'Logout',
                            listeners: {
                                click: 'onLogoutButtonClick'
                            }
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'center',
            itemId: 'content',
            layout: 'border',
            items: [
                {
                    xtype: 'panel',
                    region: 'center',
                    layout: 'border',
                    title: 'Etablissement sélectionné : ',
                    items: [
                        {
                            xtype: 'etablissement',
                            region: 'north'
                        },
                        {
                            xtype: 'tabpanel',
                            region: 'center',
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'infogentab'
                                },
                                {
                                    xtype: 'battab'
                                },
                                {
                                    xtype: 'equipementtab'
                                },
                                {
                                    xtype: 'actiontab'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'batlist',
                    region: 'west'
                }
            ]
        }
    ]

});